### ISSUE TITLE
Beth reports in

### ISSUE THREAD

**Issue by marcustisater** [marcustisater/BlogSixteen#24]
I am challenged by the posts. I want to show the full text of my post, not just the ‘…’. I can see where I would change the content file, modifying the ‘More’ variable, but I don’t see where to do that within this theme. Can you help me out?

**Comment by mark-burns** [comment]
I have the same question. The "[...]" does not link to anything and I don't see how to activate it. So the user must click over on the post in "Recent Posts" in order to see the full post.

**Comment by marcustisater** [comment]
Yeah, this is a high priority issue. I will try get it working asap. This what you can do meanwhile

If you just simply want to show the entire post on the start screen you can edit the file that's called content.php. It should be located in blogsixteen/template-parts/content.php. Open the file in the editor of WordPress or notepad and on line 26 were it says the_excerpt.

<?php
**the_excerpt**( sprintf(
/\* translators: %s: Name of current post. */
wp_kses( __( 'Continue reading %s <span class="meta-nav">&rarr;</span>', 'blogsixteen' ), array( 'span' => array( 'class' => array() ) ) ),
    the_title( '<span class="screen-reader-text">"', '"</span>', false )
) );
?>

Change the_excerpt to **the_content** instead. Now, update the file and you should see the changes. However if you want to show more words in the preview "mode" instead of the entire post you can look into this https://codex.wordpress.org/Customizing_the_Read_More 

Go ahead and give that a try,

**Comment by mark-burns** [comment]
I used this answer and added the code to functions.php. Now things work perfectly.
http://wordpress.stackexchange.com/questions/134143/how-can-i-create-a-read-more-link-using-the-excerpt-on-a-static-front-page

**Comment by marcustisater** [comment]
Great, I will try release this bugfix as quickly as possible. If you have any more feedbacks for the theme let me know :smile: 

Thanks for reporting in

**Comment by marcustisater** [comment]
fixed in upcoming version, will be release in a couple of days.
